# Generated by Django 2.2.13 on 2020-06-17 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_jgkjggh"),
        ("users", "0002_auto_20200617_0709"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ghvchgchg",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_ghvchgchg",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hgfjhf",
            field=models.ManyToManyField(
                blank=True, related_name="user_hgfjhf", to="home.CustomText"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hjghfjgj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_hjghfjgj",
                to="home.CustomText",
            ),
        ),
    ]
