# Generated by Django 2.2.13 on 2020-06-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200617_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ghvchgchg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hgfjhf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hjghfjgj',
        ),
    ]
