# Generated by Django 2.2.13 on 2020-06-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_customtext_jgkjggh"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="jgkjggh",),
    ]
